backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "produkt"
    label: "Produkt"
    folder: "src/pages/produkt"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "SEO Description", name: "description_SEO", widget: "text"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "produkt"}
      - {label: "New", name: "new", widget: "boolean", default: true}
      - {label: "Verfügbar", name: "available", widget: "boolean", default: true}
      - {label: 'Category', name: category', widget: select, options: [premium, blazer, zweiteiler, kleider, hosen, mäntel/jacken]}
      - {label: Size, name: size, widget: list, fields: [{label: "Size", name: "size", widget: "string"}]}
      - {label: Color, name: color, widget: list, fields: [{label: "Farbe", name: "color", widget: "string"}]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Preis", name: "price", widget: "number"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: Gallery, name: gallery, widget: list, fields: [{label: Image, name: image, widget: image}, {label: ALT, name: alt, widget: text}]}
      - {label: "Tags", name: "tags", widget: "list"}


  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/impressum/index.md"
        label: "Impressum"
        name: "impressum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "information-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/datenschutz/index.md"
        label: "Datenschutz"
        name: "datenschutz"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "information-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/contact/index.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "information-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/agbs/index.md"
        label: "AGBs"
        name: "agbs"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "information-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/wierrufsbelehrung/index.md"
        label: "Widerrufsbelehrung"
        name: "widerrufsbelehrung"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "information-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}